services:
  gitlab_bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      PRODUCTION: "1"
    image: registry.gitlab.com/chermnyx/vdo_test
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
