name: build-docker

on:
  push:
    branches:
      - main

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: "chermnyx/inno-arqan-gitlab:latest"
          cache-from: type=registry,ref=chermnyx/inno-arqan-gitlab:cache-main
          cache-to: type=registry,ref=chermnyx/inno-arqan-gitlab:cache-main,mode=max
