name: build-docker

on:
  push:
    branches:
      - main

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: "ghcr.io/veridevops/cicd_arqan_rqcode_gitlab:latest"
          cache-from: type=registry,ref=ghcr.io/veridevops/cicd_arqan_rqcode_gitlab:cache-main
          cache-to: type=registry,ref=ghcr.io/veridevops/cicd_arqan_rqcode_gitlab:cache-main,mode=max
